# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: [Kurong]
subtitle: []
description: ""
author: Kurong
language: en
timezone:
url: https://chenwenling.cn
root: /

# Unified Brand & Theme UI
brand:
  title: [Kurong]
  favicon: img/header.png
  hide_home_header: true
  hide_tags_header: true
  headers:
    about: img/header_img/about.gif
  menu:
    Home: /
    Tags: /tags/
    About: /about/

# Directory
source_dir: source
public_dir: public
tag_dir: tags
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# URL & Permalink
permalink: :year/:month/:day/:title/
permalink_defaults:

# Pagination
per_page: 10
pagination_dir: archives

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Extensions
theme: sunset
deploy:
  type: git
  repo: git@github.com:kurong00/kurong00.github.io.git
  branch: gh-pages

# Plugins Configuration
lazyload:
  enable: true
  onlypost: false
  isSPA: true

sitemap:
  path: sitemap.xml

hide_posts:
  filter: hidden
  public_generators: [tag]
  noindex: true

# Markdown Rendering
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: ""
  pre_class: highlight

# Third-party Services
disqus_username: kurong00
github_username: kurong00

# Legacy & Backup (Internal use)
SEOTitle: Kurong
email: kurong00@gmail.com
keyword: ""
header-img: img/header_img/title.jpg
